seed: 1

# Default number of episodes
n_episodes: 50000

# RL params
gamma: 0.99
initial_memory: 2048
n_actions: 7
metacontroller: 'multiagent'

# Learning params
batch_size: 256
lr: 0.001
update_every: 10000

# Logistics params
save_model_episode: 10000
log_episode: 100
version: "default"
base_save_path: ''

# Loss weights
dqn_loss_weight: 1

# architecture
fc_direction: 8
cumulants: 64
filters: 32
kernel_size: 3
fc: 256
